### ISSUE TITLE
Can you contribute to this repo by adding Coding Questions with Solutions in PlSQL language?

### ISSUE THREAD

**Issue by TharinduDilshan** [TharinduDilshan/InterviewQuestions2021#7]
Can you contribute to this repo by adding Coding Questions with Solutions in PlSQL language?

**Comment by sunil14701** [comment]
Hello!
I would like to work on this issue.
Could I?
Thank you so much!

**Comment by TharinduDilshan** [comment]
> Hello! I would like to work on this issue. Could I? Thank you so much!

Yes sure. You can contribute :)
